server:
  port: 10001
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 2 #契约更新间隔
    lease-expiration-duration-in-seconds: 4 #契约过期时间
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 1
spring:
  application:
    name: service0
service1: # 被调用的服务名
  ribbon: # 具体配置请看:https://github.com/Netflix/ribbon/wiki/Getting-Started  默认配置请看: com.netflix.client.config.DefaultClientConfigImpl
    ReadTimeout: 5000
    ConnectTimeout: 5000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
ribbon:
  ServerListRefreshInterval: 1000
  NFLoadBalancerPingInterval: 10 #
feign:
  hystrix:
    enabled: true
hystrix: #具体配置请看:https://github.com/Netflix/Hystrix/wiki/Configuration
  command: #service1 的所有接口方法的统一配置: personal.leo.tutorial.netflix.service0.client.config.Service1ClientConfig
    default: # 全局配置
      execution.isolation.thread.timeoutInMilliseconds: 3000
    Service1Client#tips(int): #方法级别控制.  HystrixCommandKey 的 pattern,请看 feign.Feign.configKey(Class,Method)
      execution.isolation.thread.timeoutInMilliseconds: 4000
      #类级别控制请看 personal.leo.tutorial.netflix.service0.client.config.Service1ClientConfig
